solved 4th task
Vagazzi/Homework_TMS_Web pull request #3
Opened 2023-06-25 10:56 UTC by Vagazzi

2023-06-25 20:41 UTC, Pavel-Tsishkevich requested changes

2023-06-25 20:41 UTC, Pavel-Tsishkevich commented on src/main/java/com/example/vagazzi/fourthTask/TicketService.java
> +    private static int id;
вот это не надо)

2023-06-25 20:41 UTC, Pavel-Tsishkevich commented on src/main/java/com/example/vagazzi/fourthTask/TicketService.java
> +        id++;
и тут

2023-06-25 20:41 UTC, Pavel-Tsishkevich commented on src/main/java/com/example/vagazzi/fourthTask/TicketService.java
> +        statement.setString(1, Integer.toString(id));
и тут

2023-06-25 20:41 UTC, Pavel-Tsishkevich commented on src/main/java/com/example/vagazzi/fourthTask/TicketServlet.java
> +@WebServlet(name = "ticketServlet", value = "/ticket")
путь обычно во множественном

2023-06-25 20:41 UTC, Pavel-Tsishkevich commented on src/main/java/com/example/vagazzi/fourthTask/TicketServlet.java
> +        TicketService ticketService = new TicketService();
зачем тебе каждый раз новый сервис, сделай параметром сервлета

2023-06-27 12:10 UTC, Pavel-Tsishkevich approved these changes

2023-06-27 12:10 UTC, Pavel-Tsishkevich commented on src/main/java/com/example/vagazzi/fourthTask/TicketService.java
> +    Connection dbConnection;
а почему не private?

2023-06-27 19:13 UTC, Pavel-Tsishkevich commented on src/main/java/com/example/vagazzi/fourthTask/TicketService.java
> +    Connection dbConnection;
я про переменную Connection dbConnection;

2023-06-27 20:09 UTC, Vagazzi commented on src/main/java/com/example/vagazzi/fourthTask/TicketService.java
> +    Connection dbConnection;
Забыл указать тут модификатор доступа

2023-06-27 20:09 UTC, merged